### ISSUE TITLE
Conflicting php-di/php-di and php-di/invoker versions

### ISSUE THREAD

**Issue by elazar** [mnapoli/silly#40] opened 2017-06-07 22:59 UTC
mnapoli/silly-php-di 1.1.0 requires php-di/php-di ~4.4 || ^5.0
php-di/php-di 5.0.0 requires php-di/invoker ~1.0
php-di/php-di 6.0.0 requires php-di/invoker ~2.0
mnapoli/silly 1.6.0 requires php-di/invoker ~2.0

This situation currently makes it impossible to use mnapoli/silly and mnapoli/silly-php-di together with php-di/php-di 5 (because of the php-di/invoker ~1.0 vs ~2.0 conflict) or php-di/php-di 6 (because of the php-di/php-di ~4.4 || ^5.0 vs ^6.0 conflict). I'm attempting to upgrade php-di/php-di because I've encountered PHP-DI/PHP-DI#377 under PHP 7.1, which appears to only be fixed in php-di/php-di 5 and above. I've submitted PHP-DI/PHP-DI#504 to address this in php-di/php-di 4, but I would still like the ability to use 5 or above.

```
$ composer require "php-di/php-di:^5"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mnapoli/silly ^1.6 -> satisfiable by mnapoli/silly[1.6.0].
    - mnapoli/silly-php-di 1.1.0 requires php-di/php-di ~4.4 || ^5.0 -> satisfiable by php-di/php-di[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.4.2, 5.4.3].
    - php-di/php-di 5.0.0 requires php-di/invoker ~1.0 -> satisfiable by php-di/invoker[1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.0.1 requires php-di/invoker ~1.0 -> satisfiable by php-di/invoker[1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.0.2 requires php-di/invoker ~1.0 -> satisfiable by php-di/invoker[1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.0.3 requires php-di/invoker ~1.0 -> satisfiable by php-di/invoker[1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.0.4 requires php-di/invoker ^1.0.1 -> satisfiable by php-di/invoker[1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.1.0 requires php-di/invoker ^1.0.1 -> satisfiable by php-di/invoker[1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.2.0 requires php-di/invoker ^1.1.1 -> satisfiable by php-di/invoker[1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.2.1 requires php-di/invoker ^1.1.1 -> satisfiable by php-di/invoker[1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.2.2 requires php-di/invoker ^1.1.1 -> satisfiable by php-di/invoker[1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.3.0 requires php-di/invoker ^1.1.1 -> satisfiable by php-di/invoker[1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.4.0 requires php-di/invoker ^1.3.2 -> satisfiable by php-di/invoker[1.3.2, 1.3.3].
    - php-di/php-di 5.4.1 requires php-di/invoker ^1.3.2 -> satisfiable by php-di/invoker[1.3.2, 1.3.3].
    - php-di/php-di 5.4.2 requires php-di/invoker ^1.3.2 -> satisfiable by php-di/invoker[1.3.2, 1.3.3].
    - php-di/php-di 5.4.3 requires php-di/invoker ^1.3.2 -> satisfiable by php-di/invoker[1.3.2, 1.3.3].
    - Can only install one of: php-di/invoker[2.0.0, 1.0.0].
    - Can only install one of: php-di/invoker[2.0.0, 1.0.1].
    - Can only install one of: php-di/invoker[2.0.0, 1.1.0].
    - Can only install one of: php-di/invoker[2.0.0, 1.1.1].
    - Can only install one of: php-di/invoker[2.0.0, 1.2.0].
    - Can only install one of: php-di/invoker[2.0.0, 1.3.0].
    - Can only install one of: php-di/invoker[2.0.0, 1.3.1].
    - Can only install one of: php-di/invoker[2.0.0, 1.3.2].
    - Can only install one of: php-di/invoker[2.0.0, 1.3.3].
    - mnapoli/silly 1.6.0 requires php-di/invoker ~2.0 -> satisfiable by php-di/invoker[2.0.0].
    - Installation request for mnapoli/silly-php-di ^1.1 -> satisfiable by mnapoli/silly-php-di[1.1.0].

$ composer require "php-di/php-di:^6"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mnapoli/silly ^1.6 -> satisfiable by mnapoli/silly[1.6.0].
    - Can only install one of: php-di/php-di[6.0.0-alpha2, 4.x-dev].
    - Can only install one of: php-di/php-di[6.0.0-alpha3, 4.x-dev].
    - mnapoli/silly-php-di 1.1.0 requires php-di/php-di ~4.4 || ^5.0 -> satisfiable by php-di/php-di[4.x-dev, 5.0.x-dev, 5.1.x-dev, 5.3.x-dev, 5.4.x-dev].
    - php-di/php-di 5.0.x-dev requires php-di/invoker ~1.0 -> satisfiable by php-di/invoker[1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.1.x-dev requires php-di/invoker ^1.0.1 -> satisfiable by php-di/invoker[1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.3.x-dev requires php-di/invoker ^1.1.1 -> satisfiable by php-di/invoker[1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3].
    - php-di/php-di 5.4.x-dev requires php-di/invoker ^1.3.2 -> satisfiable by php-di/invoker[1.3.2, 1.3.3].
    - php-di/php-di 6.0.0-alpha1 requires php-di/invoker ^1.3.2 -> satisfiable by php-di/invoker[1.3.2, 1.3.3].
    - php-di/php-di 6.0.x-dev requires php-di/invoker ^1.3.2 -> satisfiable by php-di/invoker[1.3.2, 1.3.3].
    - Can only install one of: php-di/invoker[2.0.0, 1.0.0].
    - Can only install one of: php-di/invoker[2.0.0, 1.0.1].
    - Can only install one of: php-di/invoker[2.0.0, 1.1.0].
    - Can only install one of: php-di/invoker[2.0.0, 1.1.1].
    - Can only install one of: php-di/invoker[2.0.0, 1.2.0].
    - Can only install one of: php-di/invoker[2.0.0, 1.3.0].
    - Can only install one of: php-di/invoker[2.0.0, 1.3.1].
    - Can only install one of: php-di/invoker[2.0.0, 1.3.2].
    - Can only install one of: php-di/invoker[2.0.0, 1.3.3].
    - mnapoli/silly 1.6.0 requires php-di/invoker ~2.0 -> satisfiable by php-di/invoker[2.0.0].
    - Installation request for mnapoli/silly-php-di ^1.1 -> satisfiable by mnapoli/silly-php-di[1.1.0].
    - Installation request for php-di/php-di ^6 -> satisfiable by php-di/php-di[6.0.0-alpha1, 6.0.0-alpha2, 6.0.0-alpha3, 6.0.x-dev].
```

**Comment by mnapoli** [comment] 2017-06-10 20:03
Hi! I'm not sure this is really a bug, for me it works well:

```
$ composer require mnapoli/silly-php-di "php-di/php-di:^5"
Using version ^1.1 for mnapoli/silly-php-di
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
    Prefetch start: total: 11
    1/11:    https://codeload.github.com/mnapoli/silly-php-di/legacy.zip/ffcfd38f20ddf43db09f1fda25faa895116c4d31
    2/11:    https://codeload.github.com/symfony/polyfill-mbstring/legacy.zip/f29dca382a6485c3cbe6379f0c61230167681937
    3/11:    https://codeload.github.com/symfony/debug/legacy.zip/e9c50482841ef696e8fa1470d950a79c8921f45d
    4/11:    https://codeload.github.com/symfony/console/legacy.zip/70d2a29b2911cbdc91a7e268046c395278238b2e
    Finished: success:4, skipped:7, failure:0, total: 11
Package operations: 11 installs, 0 updates, 0 removals
  - Installing php-di/phpdoc-reader (2.0.1) Loading from cache
  - Installing psr/container (1.0.0) Loading from cache
  - Installing container-interop/container-interop (1.2.0) Loading from cache
  - Installing php-di/invoker (1.3.3) Loading from cache
  - Installing php-di/php-di (5.4.3) Loading from cache
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.3.2) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.4.0) Loading from cache
  - Installing symfony/console (v3.3.2) Loading from cache
  - Installing mnapoli/silly (1.5.1) Loading from cache
  - Installing mnapoli/silly-php-di (1.1.0) Loading from cache
php-di/php-di suggests installing doctrine/cache (Install it if you want to use the cache (version ~1.4))
php-di/php-di suggests installing doctrine/annotations (Install it if you want to use annotations (version ~1.2))
php-di/php-di suggests installing ocramius/proxy-manager (Install it if you want to use lazy injection (version ~1.0 or ~2.0))
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/filesystem ()
symfony/console suggests installing symfony/process ()
Writing lock file
Generating autoload files
```

I'm suspecting that requiring PHP-DI 5 without updating the dependencies at the same time causes the conflicts (i.e. what's in `composer.lock`).

Could you try again with `--update-with-dependencies`:

```
$ composer require "php-di/php-di:^5" --update-with-dependencies
```

**Comment by elazar** [comment] 2017-06-10 20:59
@mnapoli Thanks for the reply. The issue was apparently that I was also explicitly including this in the `require` section of my `composer.json` file:

```js
"mnapoli/silly": "^1.6",
```

Once I removed that, `mnapoli/silly-php-di` pulled in `mnapoli/silly`, which was downgraded to 1.5.1, and that also downgraded `php-di/invoker` to 1.3.3. This removed the issue of the `php-di/invoker` version conflict blocking the installation of `php-di/php-di` 5.

All that said, I would like to see this repository support use of `php-di/php-di` 6 as well.

**Comment by mnapoli** [comment] 2017-06-11 17:34
This package uses PSR-11 so it is compatible with PHP-DI 6 (which is compliant with PSR-11).

If you want https://github.com/mnapoli/silly-php-di/ to be compatible then I think it's a matter of updating those lines https://github.com/mnapoli/silly-php-di/blob/master/composer.json#L17-L18

Feel free to open a pull request in https://github.com/mnapoli/silly-php-di, I'll close this issue in the meantime because the problem is solved.

**Closed as completed by mnapoli** 2017-06-11 17:34 UTC
